frameworkVersion: ">=1.0.0 <2.0.0"

custom:
  stage: ${opt:stage, 'dev'}
  mobilizeAmerica:
    dev: ${ssm:MOBILIZE_AMERICA_DEV}
    prod: ${ssm:MOBILIZE_AMERICA_PROD}
  mongo:
    dev: ${ssm:SLACK_FOR_SMS_MONGO_DEV}
    prod: ${ssm:SLACK_FOR_SMS_MONGO_PROD}
  customDomain:
    domainName: api.elizabethwarren.codes
    basePath: ${self:custom.stage}-events-v2
    stage: ${self:custom.stage}
    createRoute53Record: true

service: events-api

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    MONGODB_URI: ${self:custom.mongo.${self:custom.stage}}
    MOBILIZE_AMERICA_API_KEY: ${self:custom.mobilizeAmerica.${self:custom.stage}}

plugins:
  - serverless-domain-manager

functions:
  api:
    handler: src/handler.router
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
