frameworkVersion: ">=1.0.0 <2.0.0"

service: events-api

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "*"
  environment:
    EVENTS_BUCKET: 'ew-events'
    EVENTS_FILE: 'ew_events_template-events'

functions:
  api:
    handler: src/handler.router
    events:
      - http:
          path: /events
          method: any
          cors: true
      - http:
          path: /events/{proxy+}
          method: any
          cors: true
