frameworkVersion: ">=1.0.0 <2.0.0"

custom:
  stage: ${opt:stage, 'dev'}
  customDomain:
    domainName: api.elizabethwarren.codes
    basePath: ${self:custom.stage}-events
    stage: ${self:custom.stage}
    createRoute53Record: true

service: ${self:custom.stage}-events-api

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "*"
  environment:
    EVENTS_BUCKET: 'ew-events'
    EVENTS_FILE: 'ew_events_final-events'

plugins:
  - serverless-domain-manager

functions:
  api:
    handler: src/handler.router
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
